import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css"
import { Header } from "@/components/layout/header";
import { roboto_Mono } from "@/ui/typography";
import { GAScripts } from "@/config/analytics";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto_Mono.variable}>
      <GAScripts/>
      <Header/>
        {children}
        </body>
    </html>
  );
}
